name: Build and Deploy

on:
  push:
    branches:
      - master  # Kör vid push till master (eller vilken som helst branch du använder)

jobs:
  build:
    runs-on: windows-latest  # Kör på en Windows-lösning

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkar ut koden från repositoryt

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Se till att ange rätt version för .NET 8.0

    - name: Restore dependencies
      run: dotnet restore  # Återställer beroenden

    - name: Build the project
      run: dotnet build --configuration Release  # Bygger applikationen i Release-läge

    - name: Run tests (om du har tester)
      run: dotnet test --configuration Release  # Valfritt steg om du vill köra tester

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./output  # Publicera applikationen
